/**************************************************************************
This file is part of JahshakaVR, VR Authoring Toolkit
http://www.jahshaka.com
Copyright (c) 2016-2026 EXEDOS LLC (www.exedos.com)

This is free software: you may copy, redistribute
and/or modify it under the terms of the MIT License

For more information see the LICENSE file
*************************************************************************/

// defaults.primitive_table — THE ONE PRIMITIVE TABLE, as a contract
// (owner review R6 / answer Q4, lane SMALL-UI-A).
//
// src/data/primitives.h replaced FOUR copies of the primitive list plus a fifth
// partial one in the Add menu. Splitting it again is easy and silent — a fifth
// list is one `const char *[]` away — so what this suite pins is not the table's
// contents but the properties every row has to have for the four surfaces that
// read it (the tiles, the Add menu, the drop payload, the verb) to agree:
//
//   1. every row's MESH is a resource this binary actually ships, and it PARSES
//      into real geometry with UVs and TANGENTS (without float4 VES_TANGENT
//      HlmsPbs throws the moment a normal-mapped material is bound and the
//      object falls back to flat grey — CLAUDE.md, the 2026-08-29 facts);
//   2. every row with a library guid has a TILE ICON that exists and decodes;
//   3. the guids are unique AND disjoint from the reserved shader/material
//      guids they used to collide with;
//   4. the pre-renumber guids all map onto live rows, in the ONE place that
//      does it (a saved FAVOURITE is where a primitive guid persists);
//   5. Gear, Sponge, Steps and the Teapot are gone AND are refused by name;
//   6. the Teapot's MESH is still shipped and still PINNED, because four sample
//      scenes name that exact resource path in their stored scene blobs.
//
// No engine, no display: resources, files and the document's own parser.

#include <QCoreApplication>
#include <QFile>
#include <QGuiApplication>
#include <QImage>
#include <QSet>
#include <QString>

#include <cstdio>

#include "data/constants.h"
#include "data/primitives.h"
#include "irisgl/core/irisutils.h"
#include "irisgl/document/assets/mesh.h"
#include "irisgl/document/assets/vertexbuffer.h"
#include "irisgl/document/assets/vertexlayout.h"

static int failures = 0;

static void check(bool cond, const QString &what)
{
    std::printf("%s: %s\n", cond ? "ok" : "FAIL", qPrintable(what));
    if (!cond) ++failures;
}

int main(int argc, char **argv)
{
    QGuiApplication app(argc, argv);

    const QVector<primitives::Def> &table = primitives::all();
    check(table.size() >= 13,
          QStringLiteral("the table has every row (got %1)").arg(table.size()));

    // ---- 1 + 2: the mesh parses with tangents, the icon decodes -------------
    QSet<QString> guids;
    int tiles = 0;
    for (const primitives::Def &def : table) {
        const QString name = QString::fromLatin1(def.name);
        const QString mesh = QString::fromLatin1(def.mesh);

        check(QFile::exists(mesh), QStringLiteral("%1: the mesh %2 is shipped").arg(name, mesh));

        iris::MeshPtr parsed = iris::Mesh::loadMesh(mesh);
        check(!parsed.isNull() && parsed->numVerts > 0 && parsed->numFaces > 0,
              QStringLiteral("%1: it parses into real geometry (%2 verts, %3 faces)")
                  .arg(name)
                  .arg(parsed ? parsed->numVerts : 0)
                  .arg(parsed ? parsed->numFaces : 0));
        if (parsed) {
            bool hasUv = false, hasNormal = false, hasTangent = false;
            for (const iris::VertexBufferPtr &vb : parsed->getVertexBuffers()) {
                for (const iris::VertexAttribute &attrib : vb->vertexLayout.getAttribs()) {
                    if (attrib.usage == iris::VertexAttribUsage::TexCoord0) hasUv = true;
                    if (attrib.usage == iris::VertexAttribUsage::Normal) hasNormal = true;
                    if (attrib.usage == iris::VertexAttribUsage::Tangent) hasTangent = true;
                }
            }
            check(hasNormal, QStringLiteral("%1: ...with normals").arg(name));
            check(hasUv, QStringLiteral("%1: ...with UVs").arg(name));
            // The tangent is GENERATED by assimp's CalcTangentSpace, which is in
            // ImportFlags::Canonical — but only for a mesh that HAS UVs, which
            // is exactly why a new primitive authored without them would fail
            // here rather than in the user's viewport.
            check(hasTangent, QStringLiteral("%1: ...and with tangents").arg(name));
        }

        if (def.guid) {
            ++tiles;
            const QString guid = QString::fromLatin1(def.guid);
            check(!guids.contains(guid), QStringLiteral("%1: its guid %2 is unique").arg(name, guid));
            guids.insert(guid);

            check(def.icon != nullptr, QStringLiteral("%1: a tile row names an icon").arg(name));
            const QString icon = IrisUtils::getAbsoluteAssetPath(QString::fromLatin1(def.icon));
            check(QFile::exists(icon), QStringLiteral("%1: the tile icon exists (%2)").arg(name, icon));
            QImage thumb(icon);
            check(!thumb.isNull() && thumb.width() > 0 && thumb.height() > 0,
                  QStringLiteral("%1: ...and decodes (%2x%3)")
                      .arg(name).arg(thumb.width()).arg(thumb.height()));
        } else {
            // The one row with no tile is Ground, and it must stay the only one:
            // a row without a guid cannot be dragged, listed or dropped.
            check(name == QLatin1String("Ground"),
                  QStringLiteral("%1: only Ground may have no library guid").arg(name));
        }
    }
    check(tiles >= 12, QStringLiteral("at least twelve tiles (got %1)").arg(tiles));

    // ---- 3: no collision with the reserved shader/material guids ------------
    for (auto it = Constants::Reserved::BuiltinShaders.constBegin();
         it != Constants::Reserved::BuiltinShaders.constEnd(); ++it)
        check(!guids.contains(it.key()),
              QStringLiteral("no primitive guid collides with the builtin shader %1").arg(it.key()));
    for (auto it = Constants::Reserved::DefaultMaterials.constBegin();
         it != Constants::Reserved::DefaultMaterials.constEnd(); ++it)
        check(!guids.contains(it.key()),
              QStringLiteral("no primitive guid collides with the material preset %1").arg(it.value()));

    // ---- 4: the old numbering still resolves --------------------------------
    // The eight rows that survived the renumber, by their PRE-2026-09-19 guids:
    // the drop path asks primitives::byGuid, which canonicalises first.
    struct Legacy { const char *guid; const char *name; };
    const Legacy legacy[] = {
        { "00000000-0000-0000-0000-000000001000", "Plane" },
        { "00000000-0000-0000-0000-000000001001", "Cone" },
        { "00000000-0000-0000-0000-000000000002", "Cube" },
        { "00000000-0000-0000-0000-000000000003", "Cylinder" },
        { "00000000-0000-0000-0000-000000000004", "Sphere" },
        { "00000000-0000-0000-0000-000000000005", "Torus" },
        { "00000000-0000-0000-0000-000000000006", "Capsule" },
        { "00000000-0000-0000-0000-000000000008", "Pyramid" },
    };
    for (const Legacy &row : legacy) {
        const primitives::Def *def = primitives::byGuid(QString::fromLatin1(row.guid));
        check(def && QString::fromLatin1(def->name) == QLatin1String(row.name),
              QStringLiteral("the old guid %1 still resolves to %2").arg(row.guid, row.name));
    }
    // ...and the four retired rows resolve to NOTHING rather than to some other
    // shape: answering with the wrong primitive is worse than answering none.
    for (const char *gone : { "00000000-0000-0000-0000-000000000007",     // Gear
                              "00000000-0000-0000-0000-000000000009",     // Teapot
                              "00000000-0000-0000-0000-000000000010",     // Sponge
                              "00000000-0000-0000-0000-000000000011" })   // Steps
        check(primitives::byGuid(QString::fromLatin1(gone)) == nullptr,
              QStringLiteral("a retired primitive's old guid %1 resolves to nothing")
                  .arg(QString::fromLatin1(gone)));

    // ---- 5: the retired names -----------------------------------------------
    for (const char *gone : { "Gear", "Sponge", "Steps", "Teapot" }) {
        const QString name = QString::fromLatin1(gone);
        check(primitives::byName(name) == nullptr,
              QStringLiteral("%1 is not in the table").arg(name));
        const QString why = primitives::retiredReason(name);
        check(!why.isEmpty() && why.contains(name),
              QStringLiteral("%1 is refused BY NAME: %2").arg(name, why));
    }
    check(primitives::retiredReason(QStringLiteral("Dodecahedron")).isEmpty(),
          "a name that never existed gets no retirement notice (the ordinary list instead)");

    // ...and the names ARE case-insensitive, because every one of the four
    // surfaces spells them differently ("cube" from a script, "Cube" from a tile).
    check(primitives::byName(QStringLiteral("cube")) != nullptr
              && primitives::byName(QStringLiteral("  CUBE ")) != nullptr,
          "byName is case- and whitespace-insensitive");

    // ---- 6: the teapot's mesh is still shipped, and still pinned ------------
    const QString teapot = QStringLiteral(":/content/primitives/teapot.obj");
    check(QFile::exists(teapot),
          "the teapot MESH is still shipped (four sample scenes name this path in their blobs)");
    check(primitives::pinnedMeshPaths().contains(teapot),
          "...and still pinned, so opening one of those samples does not re-parse it on the UI thread");
    for (const primitives::Def &def : table)
        check(primitives::pinnedMeshPaths().contains(QString::fromLatin1(def.mesh)),
              QStringLiteral("%1's mesh is pinned").arg(QString::fromLatin1(def.name)));

    // ...and the three retired MESHES are gone from the binary altogether.
    for (const char *gone : { ":/content/primitives/gear.obj",
                              ":/content/primitives/sponge.obj",
                              ":/content/primitives/steps.obj",
                              ":/models/gear.obj" })
        check(!QFile::exists(QString::fromLatin1(gone)),
              QStringLiteral("%1 is deleted from the resources").arg(QString::fromLatin1(gone)));

    std::printf(failures ? "\nFAILED: %d\n" : "\nPASSED\n", failures);
    return failures ? 1 : 0;
}
