#!/usr/bin/env python3
"""Generate a built-in primitive's mesh, as Wavefront OBJ.

    scripts/primitives/genprimitives.py app/content/primitives

Written for the four primitives SMALL-UI-A added (Star, Wedge, Tube,
Hemisphere; owner review R6 / answer Q4, 2026-09-18), and kept because
generated geometry without its generator rots: the next primitive is a function
here and one row in src/data/primitives.h, not a trip to a DCC. The OBJs it
writes are INDEXED and deterministic, so re-running it on an unchanged table is
a no-op in git.


Every shipped primitive is modelled around its own CENTRE inside the +/-1 box
(cube.obj, sphere.obj and the rest), because the drop path rests the node's
bounding box on the surface point and the gizmo pivots on the centre.  These
follow that exactly.

Each writes v / vt / vn and f a/b/c triples with an outward winding; tangents
are generated by buildMeshV2 when a mesh carries none (CLAUDE.md), so the UVs
are what matter for them and every face here has real ones.
"""
import math, os, sys

OUT = sys.argv[1]


def write_obj(path, name, verts, uvs, norms, faces):
    with open(path, "w") as f:
        f.write("# Jahshaka primitive: %s\n" % name)
        f.write("# Generated by scripts/primitives/genprimitives.py - modelled centred in the +/-1 box.\n")
        f.write("o %s\n" % name)
        for v in verts:
            f.write("v %f %f %f\n" % v)
        for t in uvs:
            f.write("vt %f %f\n" % t)
        for n in norms:
            f.write("vn %f %f %f\n" % n)
        for tri in faces:
            f.write("f %d/%d/%d %d/%d/%d %d/%d/%d\n" % tri)


def _r(x):
    return round(x, 6) + 0.0


class Builder:
    """Pools v / vt / vn so the OBJ is INDEXED, like every shipped primitive —
    an unindexed dump of a 48x16 dome is 450 KB for 1,536 triangles."""

    def __init__(self):
        self.v, self.t, self.n, self.f = [], [], [], []
        self._vi, self._ti, self._ni = {}, {}, {}

    def _idx(self, pool, index, key):
        k = tuple(_r(x) for x in key)
        got = index.get(k)
        if got is None:
            pool.append(k)
            got = len(pool)
            index[k] = got
        return got

    def tri(self, a, b, c):
        """a, b, c are (pos, uv, normal) tuples."""
        out = []
        for p, uv, nm in (a, b, c):
            out.append(self._idx(self.v, self._vi, p))
            out.append(self._idx(self.t, self._ti, uv))
            out.append(self._idx(self.n, self._ni, nm))
        self.f.append(tuple(out))

    def quad(self, a, b, c, d):
        self.tri(a, b, c)
        self.tri(a, c, d)


def normalize(v):
    l = math.sqrt(v[0] * v[0] + v[1] * v[1] + v[2] * v[2]) or 1.0
    return (v[0] / l, v[1] / l, v[2] / l)


def face_normal(p0, p1, p2):
    u = (p1[0] - p0[0], p1[1] - p0[1], p1[2] - p0[2])
    w = (p2[0] - p0[0], p2[1] - p0[1], p2[2] - p0[2])
    return normalize((u[1] * w[2] - u[2] * w[1],
                      u[2] * w[0] - u[0] * w[2],
                      u[0] * w[1] - u[1] * w[0]))


# ---------------------------------------------------------------- Star ------
# An extruded five-pointed star: the owner named it.  Ten silhouette points
# (five outer at r=1, five inner at r=0.4), extruded +/-0.25 in z... no: in Y
# the scene is up, and every other primitive stands in the +/-1 box, so the
# star lies in the XY plane and is extruded along Z by +/-0.2, standing upright
# the way a star is drawn.
def star(points=5, outer=1.0, inner=0.40, half_depth=0.20):
    b = Builder()
    ring = []
    for i in range(points * 2):
        ang = math.pi / 2 + i * math.pi / points          # first point straight up
        r = outer if i % 2 == 0 else inner
        ring.append((math.cos(ang) * r, math.sin(ang) * r))

    def uv(p):
        return ((p[0] / outer) * 0.5 + 0.5, (p[1] / outer) * 0.5 + 0.5)

    # the two caps, as a fan from the centre
    for z, nz in ((half_depth, 1.0), (-half_depth, -1.0)):
        nm = (0.0, 0.0, nz)
        c = ((0.0, 0.0, z), (0.5, 0.5), nm)
        for i in range(len(ring)):
            j = (i + 1) % len(ring)
            a = ((ring[i][0], ring[i][1], z), uv(ring[i]), nm)
            d = ((ring[j][0], ring[j][1], z), uv(ring[j]), nm)
            if nz > 0:
                b.tri(c, a, d)
            else:
                b.tri(c, d, a)
    # the rim
    perim = 0.0
    us = []
    for i in range(len(ring)):
        us.append(perim)
        j = (i + 1) % len(ring)
        perim += math.hypot(ring[j][0] - ring[i][0], ring[j][1] - ring[i][1])
    for i in range(len(ring)):
        j = (i + 1) % len(ring)
        p0 = (ring[i][0], ring[i][1], half_depth)
        p1 = (ring[j][0], ring[j][1], half_depth)
        p2 = (ring[j][0], ring[j][1], -half_depth)
        p3 = (ring[i][0], ring[i][1], -half_depth)
        nm = face_normal(p0, p1, p2)
        u0, u1 = us[i] / perim, (us[i] + math.hypot(ring[j][0] - ring[i][0],
                                                    ring[j][1] - ring[i][1])) / perim
        b.quad((p0, (u0, 1.0), nm), (p1, (u1, 1.0), nm),
               (p2, (u1, 0.0), nm), (p3, (u0, 0.0), nm))
    return b


# --------------------------------------------------------------- Wedge ------
# A right-angle ramp: the unit cube with one edge cut away.  The VERTICAL wall
# is at z = -1 and the ramp falls away to z = +1, so a wedge dropped into a
# scene as it comes is a ramp you walk UP towards -Z, which is the direction the
# editor's default camera looks along.
def wedge():
    b = Builder()
    a0 = (-1.0, -1.0, 1.0)      # low edge, left
    a1 = (1.0, -1.0, 1.0)       # low edge, right
    a2 = (1.0, -1.0, -1.0)      # foot of the wall, right
    a3 = (-1.0, -1.0, -1.0)     # foot of the wall, left
    t2 = (1.0, 1.0, -1.0)       # top of the wall, right
    t3 = (-1.0, 1.0, -1.0)      # top of the wall, left

    nm = (0.0, -1.0, 0.0)                                   # bottom
    b.quad((a0, (0.0, 0.0), nm), (a3, (0.0, 1.0), nm), (a2, (1.0, 1.0), nm), (a1, (1.0, 0.0), nm))
    nm = (0.0, 0.0, -1.0)                                   # the vertical wall
    b.quad((a3, (0.0, 0.0), nm), (t3, (0.0, 1.0), nm), (t2, (1.0, 1.0), nm), (a2, (1.0, 0.0), nm))
    nm = face_normal(a0, a1, t2)                            # the slope
    b.quad((a0, (0.0, 0.0), nm), (a1, (1.0, 0.0), nm), (t2, (1.0, 1.0), nm), (t3, (0.0, 1.0), nm))
    nm = (-1.0, 0.0, 0.0)                                   # left triangle
    b.tri((a0, (0.0, 0.0), nm), (t3, (1.0, 1.0), nm), (a3, (1.0, 0.0), nm))
    nm = (1.0, 0.0, 0.0)                                    # right triangle
    b.tri((a1, (0.0, 0.0), nm), (a2, (1.0, 0.0), nm), (t2, (1.0, 1.0), nm))
    return b


# ---------------------------------------------------------------- Tube ------
# A hollow cylinder (a pipe): outer radius 1, inner 0.6, height 2.
def tube(seg=32, outer=1.0, inner=0.60, half=1.0):
    b = Builder()
    for i in range(seg):
        a0 = 2 * math.pi * i / seg
        a1 = 2 * math.pi * (i + 1) / seg
        u0, u1 = i / seg, (i + 1) / seg
        c0, s0 = math.cos(a0), math.sin(a0)
        c1, s1 = math.cos(a1), math.sin(a1)
        # outer wall (normals point out)
        n0, n1 = (c0, 0.0, s0), (c1, 0.0, s1)
        b.quad(((c0 * outer, half, s0 * outer), (u0, 1.0), n0),
               ((c1 * outer, half, s1 * outer), (u1, 1.0), n1),
               ((c1 * outer, -half, s1 * outer), (u1, 0.0), n1),
               ((c0 * outer, -half, s0 * outer), (u0, 0.0), n0))
        # inner wall (normals point in)
        m0, m1 = (-c0, 0.0, -s0), (-c1, 0.0, -s1)
        b.quad(((c1 * inner, half, s1 * inner), (u1, 1.0), m1),
               ((c0 * inner, half, s0 * inner), (u0, 1.0), m0),
               ((c0 * inner, -half, s0 * inner), (u0, 0.0), m0),
               ((c1 * inner, -half, s1 * inner), (u1, 0.0), m1))
        # the two rims
        up = (0.0, 1.0, 0.0)
        b.quad(((c0 * inner, half, s0 * inner), (c0 * inner * 0.5 + 0.5, s0 * inner * 0.5 + 0.5), up),
               ((c1 * inner, half, s1 * inner), (c1 * inner * 0.5 + 0.5, s1 * inner * 0.5 + 0.5), up),
               ((c1 * outer, half, s1 * outer), (c1 * outer * 0.5 + 0.5, s1 * outer * 0.5 + 0.5), up),
               ((c0 * outer, half, s0 * outer), (c0 * outer * 0.5 + 0.5, s0 * outer * 0.5 + 0.5), up))
        dn = (0.0, -1.0, 0.0)
        b.quad(((c0 * outer, -half, s0 * outer), (c0 * outer * 0.5 + 0.5, s0 * outer * 0.5 + 0.5), dn),
               ((c1 * outer, -half, s1 * outer), (c1 * outer * 0.5 + 0.5, s1 * outer * 0.5 + 0.5), dn),
               ((c1 * inner, -half, s1 * inner), (c1 * inner * 0.5 + 0.5, s1 * inner * 0.5 + 0.5), dn),
               ((c0 * inner, -half, s0 * inner), (c0 * inner * 0.5 + 0.5, s0 * inner * 0.5 + 0.5), dn))
    return b


# ---------------------------------------------------------- Hemisphere ------
# Half a unit sphere with a flat cap, centred in its own bounding box: the
# dome spans y = -0.5 .. +0.5 so the pivot is the centre of the box like every
# other primitive, not the centre of the sphere it came from.
def hemisphere(seg=32, rings=12, r=1.0):
    b = Builder()
    shift = -r * 0.5                                     # centre the +/-r/2 box

    def pos(i, j):
        phi = (math.pi / 2) * j / rings                  # 0 at the equator, pi/2 at the pole
        th = 2 * math.pi * i / seg
        return (math.cos(th) * math.cos(phi) * r,
                math.sin(phi) * r + shift,
                math.sin(th) * math.cos(phi) * r)

    def nrm(p):
        return normalize((p[0], p[1] - shift, p[2]))

    def uv(i, j):
        return (i / seg, j / rings)

    for j in range(rings):
        for i in range(seg):
            p00, p10 = pos(i, j), pos(i + 1, j)
            p11, p01 = pos(i + 1, j + 1), pos(i, j + 1)
            # wound so the OUTSIDE faces out: top-left, top-right, bottom-right,
            # bottom-left, exactly like the tube's outer wall.
            if j == rings - 1:
                b.tri((p01, uv(i, j + 1), nrm(p01)), (p10, uv(i + 1, j), nrm(p10)),
                      (p00, uv(i, j), nrm(p00)))
            else:
                b.quad((p01, uv(i, j + 1), nrm(p01)), (p11, uv(i + 1, j + 1), nrm(p11)),
                       (p10, uv(i + 1, j), nrm(p10)), (p00, uv(i, j), nrm(p00)))
    # the flat underside
    dn = (0.0, -1.0, 0.0)
    c = ((0.0, shift, 0.0), (0.5, 0.5), dn)
    for i in range(seg):
        p0, p1 = pos(i, 0), pos(i + 1, 0)
        b.tri(c, ((p1[0], shift, p1[2]), (p1[0] * 0.5 + 0.5, p1[2] * 0.5 + 0.5), dn),
              ((p0[0], shift, p0[2]), (p0[0] * 0.5 + 0.5, p0[2] * 0.5 + 0.5), dn))
    return b


for name, b in (("star", star()), ("wedge", wedge()),
                ("tube", tube()), ("hemisphere", hemisphere())):
    path = os.path.join(OUT, name + ".obj")
    write_obj(path, name.capitalize(), b.v, b.t, b.n, b.f)
    print("%-12s %5d verts %5d tris %7d bytes -> %s"
          % (name, len(b.v), len(b.f), os.path.getsize(path), path))
