#include "../../src/animation/animableproperty.h"
#include "../../src/animation/animation.h"
//#include "../../src/animation/floatcurve.h"
#include "../../src/animation/keyframeanimation.h"
//#include "../../src/animation/keyframeset.h"
//#include "../../src/animation/nodekeyframe.h"
#include "../../src/animation/propertyanim.h"
#include "../../src/animation/skeletalanimation.h"