#!/usr/bin/env python3
"""Generates the FBX UNIT-SCALE fixtures — unit_cube_{cm,m,mm}.fbx.

WHY THEY EXIST (the FBX unit-scale defect, owner report 2026-09-08 "Dreyar is
massively huge, head touches the ceiling").

An FBX file declares its own unit in GlobalSettings::UnitScaleFactor, in
CENTIMETRES PER UNIT: 1 = the file is in centimetres, 100 = metres, 0.1 =
millimetres. assimp converts it into its own metre convention only when
aiProcess_GlobalScale is in the post-process flags (FBXImporter calls
SetFileScale(UnitScaleFactor * 0.01); ScaleProcess is what consumes it).
iris::ImportFlags::Canonical did not carry the flag, so the factor was parsed
and thrown away and every Mixamo download — UnitScaleFactor 1, centimetres —
imported ONE HUNDRED TIMES too large.

These three files are the same 1x1x1 CUBE with three different declarations, so
the gate in test_importer_fbx.cpp is arithmetic rather than a vibe:

    unit_cube_cm.fbx   UnitScaleFactor 1     -> imports 0.01 m on a side
    unit_cube_m.fbx    UnitScaleFactor 100   -> imports 1.00 m on a side
    unit_cube_mm.fbx   UnitScaleFactor 0.1   -> imports 0.001 m on a side

No third-party content: ~2 KB of hand-written ASCII FBX 7.4 each, the same
shape as the sibling orphan_skin_vertex.fbx fixture.

Run:  python3 make_unit_fbx.py      (writes all three beside this script)
"""

import os

# A unit cube with its origin at a corner: every coordinate is 0 or 1, so the
# imported extent IS the file's unit expressed in metres.
V = [(0, 0, 0), (1, 0, 0), (1, 1, 0), (0, 1, 0),
     (0, 0, 1), (1, 0, 1), (1, 1, 1), (0, 1, 1)]
QUADS = [(0, 1, 2, 3), (5, 4, 7, 6), (4, 0, 3, 7),
         (1, 5, 6, 2), (4, 5, 1, 0), (3, 2, 6, 7)]
NORMALS = [(0, 0, -1), (0, 0, 1), (-1, 0, 0), (1, 0, 0), (0, -1, 0), (0, 1, 0)]


def num(x):
    """FBX ASCII numbers: integers stay integral, the rest keep their decimals."""
    return str(int(x)) if float(x) == int(x) else repr(float(x))


def write(name, unit_scale, comment):
    verts = ",".join(num(c) for v in V for c in v)
    idx = []
    for q in QUADS:
        idx += [str(q[0]), str(q[1]), str(q[2]), str(-(q[3] + 1))]
    normals = ",".join(num(c) for n in NORMALS for _ in range(4) for c in n)

    out = []
    w = out.append
    w("; FBX 7.4.0 project file\n")
    w("; ----------------------------------------------------\n")
    w("; Generated by tests/importer/fixtures/make_unit_fbx.py — do not hand-edit.\n")
    w("; %s\n\n" % comment)
    w("FBXHeaderExtension:  {\n\tFBXHeaderVersion: 1003\n\tFBXVersion: 7400\n}\n")
    w("GlobalSettings:  {\n\tVersion: 1000\n\tProperties70:  {\n")
    w("\t\tP: \"UpAxis\", \"int\", \"Integer\", \"\",1\n")
    w("\t\tP: \"UpAxisSign\", \"int\", \"Integer\", \"\",1\n")
    w("\t\tP: \"FrontAxis\", \"int\", \"Integer\", \"\",2\n")
    w("\t\tP: \"FrontAxisSign\", \"int\", \"Integer\", \"\",1\n")
    w("\t\tP: \"CoordAxis\", \"int\", \"Integer\", \"\",0\n")
    w("\t\tP: \"CoordAxisSign\", \"int\", \"Integer\", \"\",1\n")
    w("\t\tP: \"UnitScaleFactor\", \"double\", \"Number\", \"\",%s\n" % num(unit_scale))
    w("\t}\n}\n")
    w("Objects:  {\n")
    w("\tGeometry: 1000, \"Geometry::cube\", \"Mesh\" {\n")
    w("\t\tVertices: *%d {\n\t\t\ta: %s\n\t\t}\n" % (len(V) * 3, verts))
    w("\t\tPolygonVertexIndex: *%d {\n\t\t\ta: %s\n\t\t}\n" % (len(idx), ",".join(idx)))
    w("\t\tGeometryVersion: 124\n")
    w("\t\tLayerElementNormal: 0 {\n\t\t\tVersion: 101\n\t\t\tName: \"\"\n")
    w("\t\t\tMappingInformationType: \"ByPolygonVertex\"\n")
    w("\t\t\tReferenceInformationType: \"Direct\"\n")
    w("\t\t\tNormals: *%d {\n\t\t\t\ta: %s\n\t\t\t}\n" % (len(QUADS) * 4 * 3, normals))
    w("\t\t}\n")
    w("\t\tLayer: 0 {\n\t\t\tVersion: 100\n\t\t\tLayerElement:  {\n")
    w("\t\t\t\tType: \"LayerElementNormal\"\n\t\t\t\tTypedIndex: 0\n\t\t\t}\n\t\t}\n")
    w("\t}\n")
    w("\tModel: 2000, \"Model::cube\", \"Mesh\" {\n\t\tVersion: 232\n")
    w("\t\tProperties70:  {\n")
    w("\t\t\tP: \"Lcl Translation\", \"Lcl Translation\", \"\", \"A\",0,0,0\n")
    w("\t\t}\n\t\tShading: T\n\t\tCulling: \"CullingOff\"\n\t}\n")
    w("}\n")
    w("Connections:  {\n\tC: \"OO\",2000,0\n\tC: \"OO\",1000,2000\n}\n")

    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), name)
    with open(path, "w") as f:
        f.write("".join(out))
    print("wrote %s (unit scale %s)" % (path, unit_scale))


write("unit_cube_cm.fbx", 1,
      "A 1x1x1 cube declared in CENTIMETRES: it must import 0.01 m on a side.")
write("unit_cube_m.fbx", 100,
      "The same cube declared in METRES: it must import 1 m on a side, unchanged.")
write("unit_cube_mm.fbx", 0.1,
      "The same cube declared in MILLIMETRES: it must import 0.001 m on a side.")
